DROP TABLE IF EXISTS users; 

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_name TEXT, 
    user_email TEXT NOT NULL, 
    user_password TEXT NOT NULL,
    user_username TEXT, 
    user_city TEXT, 
    profile_img TEXT
);